name: Build and deploy

on:
  push:
    branches: ['main', 'AK-new-backend']

jobs:
  push_to_registry:
    name: Push Docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          path: AK-new-backend

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.menuma.online
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: menuma/menuma-frontend

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.menuma.online/menuma/frontend:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NEXT_PUBLIC_BACKEND_BASE_API=${{ vars.NEXT_PUBLIC_BACKEND_BASE_API }}
            NEXT_PUBLIC_MENUMA_DOMAIN=${{ vars.NEXT_PUBLIC_MENUMA_DOMAIN }}

      - name: Call API to update server
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ secrets.SERVER_UPDATE_URL }}
          accept: 200
          #          headers:  '{ "Authorization": "Bearer mytoken" }'
          headers: ${{ secrets.SERVER_UPDATE_HEADER }}
          timeout: 10000
          retries: 3
