name: Check and Test

on:
  - push
  - pull_request

jobs:
  cache-install:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      workflows: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store

      - name: Install dependencies
        run: pnpm i

      - name: Format Code
        run: npm run format

      - name: Commit format changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Prettier format"
          skip_dirty_check: false
          commit_user_name: "Github Action"

      - name: Run CI
        run: npm run ci
